name: 'Terraform apply'
description: 'Runs Terraform apply in the given directory'
inputs:
  image-name:
    description: 'The name of the container image to use'
    required: false
    default: ''
  tf-api-token:
    description: 'The Terraform Cloud API token'
    required: true
  tf-cloud-organization:
    description: 'The name of the Terraform Cloud organization'
    required: true
  tf-cloud-workspace:
    description: 'The name of the Terraform Cloud workspace'
    required: true
  working-directory:
    description: 'The path to the Terraform working directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set Terraform Cloud environment variables
      shell: bash
      run: |
        echo "TF_CLOUD_ORGANIZATION=${{ inputs.tf-cloud-workspace }}" >> $GITHUB_ENV
        echo "TF_WORKSPACE=${{ inputs.tf-cloud-workspace }}" >> $GITHUB_ENV
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ inputs.tf-api-token }}
    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
    - name: Terraform Apply
      id: apply
      env:
        TF_VAR_container_image: ${{ inputs.image-name }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform apply -auto-approve -input=false
