trigger: none

pr:
  - main

pool:
  vmImage: '$(image)'

variables:
  image: 'ubuntu-latest'
  solutionPath: 'NoPlan.sln'
  configuration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Acquire .NET 6 SDK'
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages for solution'
    inputs:
      command: 'restore'
      projects: '$(solutionPath)'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: 'Build the solution'
    inputs:
      command: 'build'
      projects: '$(solutionPath)'
      arguments: '--no-restore --configuration $(configuration)'
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '$(solutionPath)'
      arguments: '--no-build --configuration $(configuration) --collect "Code coverage"'