version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: otel-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: otel-jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "16686:16686"

  loki:
    image: grafana/loki:latest
    container_name: otel-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    depends_on:
      - jaeger
      - loki
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: otel-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    user: root
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=NoPlan1234!
      - MSSQL_PID=Developer
    volumes:
      - ./sql/data/:/var/opt/mssql/data/"
      - ./sql/log/:/var/opt/mssql/log/"
      - ./sql/secrets/:/var/opt/mssql/secrets/"

volumes:
  grafana_data:
  prometheus_data:
