name: Build solution and run tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Directory.Packages.props'
      - 'NoPlan.sln'
      - 'src/**'
      - 'tests/**'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build project and run tests
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: 'Release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet test -c ${{ env.CONFIGURATION }} --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
        with:
          reports: 'coverage/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura'
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coveragereport/Cobertura.xml'
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'codecoverage'
          recreate: true
          path: code-coverage-results.md
