name: Deploy to production environment

on:
  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: ${{ vars.REGISTRY_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}

jobs:
  tag:
    name: Tag container image for production
    runs-on: ubuntu-latest
    environment: production
    env:
      SOURCE_IMAGE_NAME: ${{ vars.REGISTRY_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.sha }}
      TARGET_IMAGE_NAME: ${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Tag staging image as production
        run: |
          az acr import \
          --name ${{ vars.REGISTRY_NAME }} \
          --source ${{ env.SOURCE_IMAGE_NAME }} \
          --image ${{ env.TARGET_IMAGE_NAME }}

  apply:
    name: Apply production environment
    runs-on: ubuntu-latest
    needs:
      - tag
    defaults:
      run:
        working-directory: ./infra/production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -var container_image="${{ env.IMAGE_NAME }}"
