name: Deploy to Azure Container Apps

on:
  push:
    branches:
      [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/deploy.yml'

  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
env:
  APP_NAME: aca-noplan-dev-001
  RESOURCE_GROUP: rg-noplan-dev-001
  REGISTRY_NAME: crnoplandev001

jobs:
  build:
    name: Building the Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${ env.REGISTRY_NAME }.azurecr.io
          username: ${ secrets.AZURE_CLIENT_ID }
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ env.REGISTRY_NAME }.azurecr.io/noplan-api:${{ github.sha }}
          file: ./src/NoPlan.Api/Dockerfile
          context: .

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ${ env.APP_NAME } -g ${ env.RESOURCE_GROUP } --server ${ env.REGISTRY_NAME }.azurecr.io
            az containerapp update -n ${ env.APP_NAME } -g ${ env.RESOURCE_GROUP } --image ${ env.REGISTRY_NAME }.azurecr.io/noplan-api:${{ github.sha }}
