name: Deploy infrastructure to the global and staging environments

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-staging-and-global.yml'

  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}

jobs:
  apply-global:
    name: Apply to global environment
    runs-on: ubuntu-latest
    environment: global
    env:
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
    defaults:
      run:
        working-directory: ./infra/global
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false

  apply-staging:
    name: Apply to staging environment
    runs-on: ubuntu-latest
    environment: staging
    env:
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
    defaults:
      run:
        working-directory: ./infra/staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false
