name: Dummy Terraform validate and plan

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!infra/**'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Terraform configuration
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0

  plan-staging:
    name: Plan staging environment
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0

  plan-production:
    name: Plan production environment
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0

  plan-global:
    name: Plan global environment
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0
