name: Terraform validate and plan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ vars.REGISTRY_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.sha }}

jobs:
  validate:
    name: Validate Terraform configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform validate
        uses: ./.github/actions/terraform-validate
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./infra

  plan-staging:
    name: Plan staging environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          environment-name: Staging
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          working-directory: ./infra/staging

  plan-production:
    name: Plan production environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          environment-name: Production
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          working-directory: ./infra/production

  plan-global:
    name: Plan global environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          environment-name: Global
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          working-directory: ./infra/global
